### ISSUE TITLE
showing left or right side always.

### ISSUE THREAD

**Issue by ZzzzZesty** [cbyrne/peep#13]
![6B0C6531-55A6-4652-BA55-B9EB5CD3FD9C](https://user-images.githubusercontent.com/63427185/82946066-b9752280-9f6b-11ea-83e8-771b7549a1aa.jpeg)
![8E5ED2B5-ECEE-4ED2-BAEC-CFFD422DE418](https://user-images.githubusercontent.com/63427185/82946072-bbd77c80-9f6b-11ea-9b76-d9157ab0dfd0.jpeg)
![7C25789C-4FE1-49B1-A2B7-3C9002A6CCD9](https://user-images.githubusercontent.com/63427185/82946109-ca259880-9f6b-11ea-8ad9-c8f9ef511413.jpeg)
![C9DF87E1-7201-43DF-9EEA-96B39544D069](https://user-images.githubusercontent.com/63427185/82946111-cabe2f00-9f6b-11ea-929b-033513e5608c.jpeg)

**Comment by cbyrne** [comment]
Fixed in latest update
