### ISSUE TITLE
Mismatching on/off switch

### ISSUE THREAD

**Issue by BOBBIESWAG** [cbyrne/peep#14]
When I go to my lock screen and tap the status bar it disappears, but if I continue to login to my phone, it displays the time on the status bar with nothing else. From then on until I respring, this will alternate, from just the time, to everything else, just the time, etc. 

Great tweak and can’t wait until it is supported system-wide!

iPhone 7 IOS 13.5
Tweak list: (Oh And I don’t know what the cross out lines on some tweaks is there I just dumped the list with [[flame]]. Sorry!)
7-zip (POSIX): 16.02-1
AppList: 1.5.16
AppStore++: 0.9.10
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
Barmoji: 2020.3
Base Structure: 1-5
Batchomatic: 4.3.1
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
BlurGround: 1.1.2
Bourne-Again SHell: 5.0.3-2
BrowserDefault: 1.9.9
bzip2: 1.0.6-1
CA Certs: 0.0.2
Cask 2: 1.1.1
CastSwitcher: 1.2-3
Central: 1.0.6
Cephei: 1.15
ClearDock12: 1.0.0
ColorMeNotifs: 1.4.2
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
csdbgd: 2.1.0-248
Cydia Installer: 1.1.33
Cydia Translations: 1.1.32~b1
Cylinder: 1.1
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
DeleteCut: 0.4
Diff Utilities: 3.6-1
DigitalBattery13: 1.0.0
diskdev-cmds: 593.221.1-1
DolphiniOS: 2.2.3-4
Dress 👗: 1.0-beta
file: 5.35-2
Filza File Manager: 3.7.5-12
Find Utilities: 4.6.0-2
Flame: 1.3
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
Hide Labels: 0.0.1-10
HideYourApps: 1.3.0
HYI Repo Icons: 8.0.4
iCleaner Pro: 7.8.2
iOS Firmware: 13.5
iPhone Firmware (/sbin): 0-1
KarenLocalizer: 1.0.5
KarenPrefs: 1.5
Keyboard Accio: 2.4
KSBA: 1.3.5-1
Launch Daemon Controller: 23-1
LetMeDecline: 1.0
libcolorpicker: 1.6.7
libCozy: 0.1.1
libCSColorPicker: 1.0.3
libCSPreferences: 1.4.2
Liberty Lite: 0.2.10
libidn2: 6.1.2-1
libimagepicker: 1.0.4
libMRYIPC: 1.0
libnotifications: 0.2-4
libpackageinfo (cokepokes): 1.1.0.1-3
libplist: 2.0.0-2
libsparkcolourpicker: 1.0.0
libswift4: 4.2.1-2
libsymbolicate: 1.9.0-1
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.2+g5420cb5-1
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
MenushkaPrefs: 1.2.3
mikoto: 4.0.3
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1+20181013-1
New GNU Portable Threads: 1.6-1
NoClutter: 1.1.2
NoDNDBanner: 0.0.1
noNotch: 1.2-b8
OpenSSL 1.0 Libraries: 1.0.2s-1
OpenSSL 1.1.1 Libraries: 1.1.1c-1
p11-kit: 0.23.12-1
peep: 1.0
PreferenceLoader: 2.2.4
PreferenceOrganizer 2: 4.0.8
Profile Directory: 0-1
PullToRespring: 1.2
readline: 8.0-1
ReProvision: 0.5.2~EOL
RocketBootstrap: 1.0.9
sed: 4.5-1
shell-cmds: 118-8
ShortcutEnabler: 1.2.1
SimpleLS2: 1.3.1-6
Substrate Safe Mode: 0.9.6003
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TechSupport Framework (cokepokes): 1.5.0.1-2
TSS Saver: 1.2.0
tweakCompatible: 0.1.5
UIKit Tools: 1.1.17-1
Unc0ver Policy Softener: 1.0.0
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
WeatherGround: 1.0
XZ Utils: 5.2.4-4
zip: 2.32-1

**Comment by BOBBIESWAG** [comment]
![86BEC8AC-E8AF-4855-A8EF-C15D648A063A](https://user-images.githubusercontent.com/29669099/82960937-3dc4b580-9fff-11ea-889b-e1c144102cf9.png)
![ADC62281-781C-4361-B55B-85D0354D1969](https://user-images.githubusercontent.com/29669099/82960951-461cf080-9fff-11ea-8fbf-2fe9f3562db9.png)

Here are some screen shots

**Comment by cbyrne** [comment]
Fixed in latest update
