### ISSUE TITLE
lag on statusbar

### ISSUE THREAD

**Issue by 56aluminium** [cbyrne/peep#2]
Lag on statusbar when opening and closing folders and also when going to Homescreen From an app 

Device : iPhone10,6 / iPhone X
iOS version : 13.4 
jailbreak : Checkra1n 

installed tweaks : 
- liberty lite 
- Compactor 
- peep
- rocket for instagram
- WatchSounds
- Choicy
- Globalize

Video about the issue : 
[Unlisted Youtube Link](https://youtu.be/dzBf84uAvFI)

**Comment by cbyrne** [comment]
Fixed in latest update
