### ISSUE TITLE
Peep

### ISSUE THREAD

**Issue by asvpluis23** [cbyrne/peep#5]
If I have my wifi off, I tap status bar to make it disappear everything works well, but if I turn my wifi on while it's disappeared then wifi glitches and shows when it's supposed to be disappeared. This can go with any icon.
![8026A3C1-820A-4307-8A92-AAE4DAD3938C](https://user-images.githubusercontent.com/63982909/79702144-3d026c00-8268-11ea-807e-95603359a281.jpeg)
![2F704C01-1870-4AA8-82CC-1E34DB774EB4](https://user-images.githubusercontent.com/63982909/79702145-3f64c600-8268-11ea-8c22-2ace75be0657.jpeg)

**Comment by cbyrne** [comment]
Fixed in latest update
