### ISSUE TITLE
"Stop calculating time"

### ISSUE THREAD

**Issue by jinshah05** [cbyrne/peep#8]
Why is the peep tweak "Stop calculating time" whenever hides the statusbar. Is this any bug?

Because whenever I hide the statusbar and seeing time from my incoming call UI, it shows the time when I hide the statusbar and the time will stop after that. I have trouble seeing the time when I am on call.

**Comment by cbyrne** [comment]
Fixed in latest update

**Comment by jinshah05** [comment]
Thank you
